(require 'whitespace)
(setq whitespace-style '(face tabs tab-mark spaces lines-tail empty))
(global-whitespace-mode 1)
(setq-default tab-width 4 indent-tabs-mode nil)
(setq indent-tabs-mode nil)
